name: McInfected
version: ${project.version}
api-version: "1.16"
main: com.ericlam.mc.mcinfected.main.McInfected
depend:
  - Minigames-Core
  - LibsDisguises
  - CustomCSWeapon
softdepend:
  - MinigameMiscs
commands:
  inf-arena:
    description: inf arena setup command