name: McInfected
version: 0.0.7-SNAPSHOT
api-version: "1.13"
main: com.ericlam.mc.mcinfected.main.McInfected
depend:
  - Minigames-Core
  - LibsDisguises
  - CustomCSWeapon
softdepend:
  - TintHealth
commands:
  inf-arena:
    description: inf arena setup command