name: McInfected
version: 0.0.1-SNAPSHOT
api-version: "1.13"
main: com.ericlam.mc.mcinfected.main.McInfected
depend:
  - Minigames-Core
  - LibsDisguises
commands:
  inf-test:
    description: test command
  inf-arena:
    description: inf arena setup command